url: https://webfixery.com
baseurl: /

# Site settings
title: Apps, Web Apps, Custom Sites, Automation, Bug Fixing | General Web Fixery
email: webfixery@squarehq.com
description: "Modern websites, web development, business automation, and scripting. Built in Los Angeles."


# Team names, titles and social links
people:
- name: Tyler Conover
  pic: 1
  position: Product Lead
  social:
    - title: twitter
      url: https://twitter.com/tylerhq
    - title: facebook
      url: https://facebook.com/tylerhq

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/webfixery
  - title: facebook
    url: https://facebook.com/webfixery
  - title: github
    url: http://github.com/webfixery

# Postal address (add as many lines as necessary)
address:
  - line: 17320 Burbank Blvd, Suite 30
  - line: Los Angeles, CA 91316

# Build settings
markdown: kramdown
permalink: pretty
